//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_and_Spa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salon_Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salon_Owner()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int CorporateId { get; set; }
        public string Name_Of_The_Salon { get; set; }
        public string EmailId { get; set; }
        public string Location { get; set; }
        public string Password { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
    }
}
